---
version: "3.7"
services:
  "terraform-documentation":
    container_name: terraform-documentation
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - 3000:3000
