name: Documentation
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for all feature branches
  push:
    branches: [ "**" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm ci

      - name: Update documentation files
        run: node src/prepare-documentation-files.js

  build:
    runs-on: ubuntu-latest
    needs: update_documentation
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ASTRO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ASTRO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ASTRO_AWS_REGION }}

      - name: Install modules
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Prepare artifact
        run: zip -r artifact.zip node_modules dist

      - name: Upload the build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: artifact.zip
          retention-days: 1


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v3
        with:
          name: build-output

      - name: Prepare artifact
        run: |
          unzip artifact.zip
          rm artifact.zip 

      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://${{ secrets.ASTRO_BUCKET_ARN }}

#      - name: Create CloudFront invalidation
#        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
